
name: 1. Build for Tests (Development)

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build_test_environment_development:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions Shared Files (for Emulators)
        run: npm run build:shared --prefix functions
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Prepare Functions artifact for testing
        shell: bash
        run: |
          set -e
          mkdir -p functions_artifact_staging_test/src
          mkdir -p functions_artifact_staging_test/lib/shared
          cp -r functions/src/* functions_artifact_staging_test/src/
          if [ ! -d "functions/lib/shared" ] || [ -z "$(ls -A functions/lib/shared)" ]; then
            echo "Error: functions/lib/shared not found or is empty after build:shared."
            exit 1
          else
            cp -r functions/lib/shared/* functions_artifact_staging_test/lib/shared/
          fi
          cp functions/package.json functions_artifact_staging_test/
          cp functions/package-lock.json functions_artifact_staging_test/
          ls -R functions_artifact_staging_test
        
      - name: Upload Functions source and shared build artifact (for test workflow - Development)
        uses: actions/upload-artifact@v4
        with:
          name: functions-src-and-shared-for-test-development
          path: functions_artifact_staging_test/ 
          retention-days: 1
          if-no-files-found: error
