/**
 * @fileoverview
 * This module defines the `Chart` component, which is a simple React component
 * used to display an image-based chart within the application.
 */

import Image from 'next/image';

/**
 * The props for the `Chart` component.
 * @interface
 */
interface ChartProps {
  /**
   * The source URL of the chart image.
   * @type {string}
   */
  src: string;

  /**
   * The alternative text for the chart image, used for accessibility.
   * @type {string}
   */
  alt: string;
}

/**
 * A simple React functional component that renders an image.
 *
 * This component is used to display the charts that are generated by the backend.
 * It takes the public URL of the chart image and an alt text as props.
 *
 * @param {ChartProps} props - The props for the component.
 * @returns {JSX.Element} An `img` element representing the chart.
 */
const Chart: React.FC<ChartProps> = ({ src, alt }) => {
  return (
    <Image
      src={src}
      alt={alt}
      className="w-full h-auto object-contain" // object-contain to prevent stretching/distortion
      width={0} // Required by Next.js Image component, but set to 0 as the image is responsive
      height={0} // Required by Next.js Image component, but set to 0 as the image is responsive
      sizes="100vw" // Indicates the image will take up 100% of the viewport width
    />
  );
};

export default Chart;
