
import { AppHeader } from '@/components/app-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div className="flex min-h-screen flex-col bg-muted/30">
      <AppHeader />
      <main className="container mx-auto max-w-3xl py-8 px-4 flex-1">
        <div className="mb-6">
          <Link href="/login" className="text-sm text-primary hover:underline flex items-center">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Login
          </Link>
        </div>
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="text-3xl font-bold text-primary">Terms of Service</CardTitle>
            <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-US')}</p>
          </CardHeader>
          <CardContent className="prose prose-slate max-w-none dark:prose-invert">
            <p><em><strong>Attention:</strong> This is a sample terms of service and does not constitute legal advice. Adapt this content to your specific needs and consult a legal professional.</em></p>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing and using the EMA - Electric Magnitudes Analizer application ("Service"), you agree to comply with these Terms of Service ("Terms"). If you do not agree with these Terms, do not use the Service.</p>

            <h2>2. Description of Service</h2>
            <p>EMA - Electric Magnitudes Analizer is a tool that allows users to upload CSV files containing electrical power quality data. The Service uses artificial intelligence (Genkit and Google AI) to analyze this data against ANEEL normative resolutions and generate compliance reports. The service also offers a chat interface to interact with the reports.</p>

            <h2>3. User Accounts</h2>
            <p>To use the Service, you must register using a Google account. You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.</p>

            <h2>4. Use of the Service and User Data</h2>
            <ul>
              <li>You are solely responsible for the content of the CSV files you upload ("User Data") and warrant that you have all necessary rights to upload and process this data.</li>
              <li>You grant EMA - Electric Magnitudes Analizer a worldwide, non-exclusive, royalty-free, transferable license to use, reproduce, modify, and process your User Data solely for the purpose of providing and improving the Service to you.</li>
              <li>You agree not to use the Service for any illegal or unauthorized purposes.</li>
            </ul>

            <h2>5. Artificial Intelligence Processing</h2>
            <p>The Service uses artificial intelligence (AI) models to analyze your User Data and generate reports. While we strive to provide accurate results, the analyses and reports generated by AI are provided "as is" and may contain errors or omissions. The Service is not intended to replace the professional judgment of qualified engineers or legal advice.</p>
            <p>The results generated by AI should not be considered definitive technical or legal advice. You are responsible for verifying the accuracy and appropriateness of the reports before making any decisions based on them.</p>

            <h2>6. Intellectual Property</h2>
            <ul>
              <li><strong>Our Service:</strong> We own all rights, titles, and interests in and to the Service, including all software, design, text, graphics, and other content (excluding your User Data and reports generated from it).</li>
              <li><strong>Your Data and Reports:</strong> You retain all ownership rights to your User Data. Reports generated from your User Data are your property, subject to our license to operate the Service.</li>
            </ul>

            <h2>7. Disclaimer of Warranties</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, NOR THAT THE ANALYSIS RESULTS WILL BE COMPLETELY ACCURATE OR RELIABLE.</p>

            <h2>8. Limitation of Liability</h2>
            <p>IN NO EVENT SHALL EMA - ELECTRIC MAGNITUDES ANALIZER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (III) ANY CONTENT OBTAINED FROM THE SERVICE; AND (IV) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.</p>

            <h2>9. Termination</h2>
            <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

            <h2>10. Changes to Terms</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

            <h2>11. Governing Law</h2>
            <p>These Terms shall be governed and construed in accordance with the laws of Brazil, without regard to its conflict of law provisions.</p>

            <h2>12. Contact</h2>
            <p>If you have any questions about these Terms, please contact us via email at: [Your Contact Email Address].</p>
          </CardContent>
        </Card>
      </main>
      <footer className="py-6 text-center text-sm text-muted-foreground border-t border-border/50 bg-muted/20">
        © {new Date().getFullYear()} EMA - Electric Magnitudes Analizer. All rights reserved.
        <div className="mt-1">
          <Link href="/privacy-policy" className="hover:underline">Privacy Policy</Link>
          {' | '}
          <Link href="/terms-of-service" className="hover:underline">Terms of Service</Link>
        </div>
      </footer>
    </div>
  );
}

    