name: 0a. Run Backend Unit Tests

on: push

jobs:
  test_backend_unit:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    # No environment needed for unit tests usually
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies (for Jest, etc.)
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      # Unit tests for backend (functions) usually don't need emulators or extensive env vars
      - name: Run Backend Unit Tests
        run: npm run test:unit:backend
        env:
          CI: true
          # Minimal env vars if any specific unit test needs them, but ideally not.
          # GCLOUD_PROJECT: 'electric-magnitudes-analizer' # Example if needed by a util
          # FIREBASE_CONFIG: '{}' # Minimal config if firebase-admin is initialized
          # NEXT_PUBLIC_FIREBASE_CONFIG: '{}'
          # NEXT_PUBLIC_GEMINI_API_KEY: 'dummy-backend-unit-test-key'
          # Ensure paths in tests expecting GOOGLE_APPLICATION_CREDENTIALS are handled (e.g., by mocking or not running those specific tests in unit scope)
          # For true unit tests, external services like Pub/Sub should be mocked.
          # The `firebase-admin` mock in unit tests should handle initializations.
