name: 0b. Run Frontend Unit Tests

on:
  workflow_run:
    workflows: ['0a. Run Backend Unit Tests']
    types:
      - completed

jobs:
  test_frontend_unit:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    # No environment needed for unit tests usually
    if: github.event.workflow_run.conclusion == 'success' # Only run if backend unit tests passed
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }} # Checkout the same commit

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      # Functions dependencies might be needed if frontend unit tests import shared code
      # that indirectly depends on functions node_modules.
      - name: Install Firebase Functions dependencies (for shared code)
        run: npm ci --prefix functions

      - name: Run Frontend Unit Tests
        run: npm run test:unit:frontend
        env:
          CI: true
          # Environment variables for frontend unit tests
          # These should ideally be mocked by the tests themselves.
          NEXT_PUBLIC_FIREBASE_CONFIG: '${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG_TESTING || "{}" }}' # Use a testing config or a valid dummy
          NEXT_PUBLIC_GEMINI_API_KEY: '${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY_TESTING || "dummy-frontend-unit-test-key" }}'
          # `firebase/auth` mocks should handle auth state.
          # `firebase/functions` mocks (httpsCallable) should handle function calls.
