
name: 1. Build for Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_environment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write # Required for uploading artifacts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions Shared Files (for Emulators)
        run: npm run build:shared --prefix functions
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Prepare Functions artifact for testing
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          echo "Preparing artifact staging directory..."
          mkdir -p functions_artifact_staging_test/src
          mkdir -p functions_artifact_staging_test/lib/shared # Ensure lib/shared dir exists
          
          echo "Copying functions/src..."
          cp -r functions/src/* functions_artifact_staging_test/src/
          
          echo "Checking for functions/lib/shared..."
          if [ -d "functions/lib/shared" ]; then
            echo "Copying functions/lib/shared..."
            cp -r functions/lib/shared/* functions_artifact_staging_test/lib/shared/
          else
            echo "Error: functions/lib/shared not found after build:shared. Cannot prepare artifact."
            exit 1
          fi
          
          echo "Copying functions/package.json and package-lock.json..."
          cp functions/package.json functions_artifact_staging_test/
          cp functions/package-lock.json functions_artifact_staging_test/
          
          echo "Listing contents of staging directory:"
          ls -R functions_artifact_staging_test
        shell: bash

      - name: Upload Functions source and shared build artifact (for test workflow)
        uses: actions/upload-artifact@v4
        with:
          name: functions-src-and-shared-for-test
          path: functions_artifact_staging_test/ # Upload content of staging directory
          retention-days: 1
          if-no-files-found: error # Fail the step if no files are found
