
name: 1. Build for Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_environment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions Shared Files (for Emulators)
        run: npm run build:shared --prefix functions
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Prepare Functions artifact for testing
        run: |
          mkdir -p functions_artifact_staging_test/lib
          cp -r functions/src/* functions_artifact_staging_test/src/
          if [ -d "functions/lib/shared" ]; then
            cp -r functions/lib/shared/* functions_artifact_staging_test/lib/shared/
          else
            echo "Error: functions/lib/shared not found after build:shared. Cannot prepare artifact."
            exit 1
          fi
          cp functions/package.json functions_artifact_staging_test/
          cp functions/package-lock.json functions_artifact_staging_test/

      - name: Upload Functions source and shared build artifact (for test workflow)
        uses: actions/upload-artifact@v4
        with:
          name: functions-src-and-shared-for-test
          path: functions_artifact_staging_test/ # Upload content of staging directory
          retention-days: 1
