
name: 1. Build for Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_environment:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Esta job só precisa ler o código e fazer build
      actions: write # Para fazer upload de artefatos, se necessário, ou permitir que outros workflows o vejam

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions for Emulators
        run: npm run build --prefix functions
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload Functions build artifact (for test workflow)
        uses: actions/upload-artifact@v4
        with:
          name: functions-build-for-test
          path: functions/lib # Apenas o diretório 'lib' construído
          retention-days: 1 # Artefato só é necessário para o próximo workflow
