
name: 1. Build for Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_environment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions Shared Files (for Emulators)
        run: npm run build:shared --prefix functions
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload Functions source and shared build artifact (for test workflow)
        uses: actions/upload-artifact@v4
        with:
          name: functions-src-and-shared-for-test
          path: |
            functions/src
            functions/lib/shared 
            functions/package.json
            functions/package-lock.json
          retention-days: 1
