name: 1. Run Integration Tests

on:
  workflow_run:
    workflows: ['0b. Run Frontend Unit Tests']
    types:
      - completed

jobs:
  test_integration:
    name: Integration Tests with Emulators
    runs-on: ubuntu-latest
    environment: test # Assuming 'test' environment has necessary secrets for emulators/integration
    if: github.event.workflow_run.conclusion == 'success' # Only run if frontend unit tests passed
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }} # Checkout the same commit

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions Shared Files (for Emulators)
        run: npm run build:shared --prefix functions
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Get Firebase CLI version
        id: firebase_version
        run: echo "CLI_VERSION=$(firebase --version)" >> $GITHUB_OUTPUT

      - name: Cache Firebase Emulators
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ steps.firebase_version.outputs.CLI_VERSION }}
          restore-keys: |
            ${{ runner.os }}-firebase-emulators-

      - name: Run Integration Tests
        run: npm run test:integration # Use the new specific script
        env:
          CI: true
          FIRESTORE_EMULATOR_HOST: ${{ secrets.FIRESTORE_EMULATOR_HOST }}
          FIREBASE_AUTH_EMULATOR_HOST: ${{ secrets.FIREBASE_AUTH_EMULATOR_HOST }}
          FIREBASE_STORAGE_EMULATOR_HOST: ${{ secrets.FIREBASE_STORAGE_EMULATOR_HOST }}
          FIREBASE_DATABASE_EMULATOR_HOST: ${{ secrets.FIREBASE_DATABASE_EMULATOR_HOST }}
          FUNCTIONS_EMULATOR_HOST: ${{ secrets.FUNCTIONS_EMULATOR_HOST }}
          FIREBASE_FUNCTIONS_EMULATOR_ORIGIN: ${{ secrets.FIREBASE_FUNCTIONS_EMULATOR_ORIGIN }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }} # Project ID for emulators
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }} # Full server config if needed by Admin SDK in tests
          FIREBASE_WEB_CONFIG: ${{ secrets.FIREBASE_WEB_CONFIG }} # Deprecated, use NEXT_PUBLIC_FIREBASE_CONFIG
          GCP_REGION: ${{ secrets.GCP_REGION }}
          NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }} # For client SDK in tests
          # NEXT_PUBLIC_FIREBASE_WEB_CONFIG is deprecated.
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }} # For Genkit flows in tests
          # GOOGLE_APPLICATION_CREDENTIALS might be needed if integration tests use Admin SDK to talk to live Pub/Sub etc.
          # For emulated Pub/Sub, ensure PUBSUB_EMULATOR_HOST is set, or Admin SDK is configured for it.
          # PUBSUB_EMULATOR_HOST: "localhost:8085" # Example if tests need Pub/Sub emulator
