
name: 2. Run Integration Tests

on:
  workflow_run:
    workflows: ["1. Build for Tests"] 
    types:
      - completed

jobs:
  test_application:
    runs-on: ubuntu-latest
    # Define o ambiente para este job
    environment: test 
    if: github.event.workflow_run.conclusion == 'success' 
    permissions:
      contents: read 
      actions: read # Required to download artifacts from other workflow runs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }} # Checkout the same commit that triggered workflow 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Download Functions source and shared build artifact
        uses: actions/download-artifact@v4
        with:
          name: functions-src-and-shared-for-test
          path: functions 
          run-id: ${{ github.event.workflow_run.id }} # Specify the run ID of the triggering workflow
          github-token: ${{ secrets.ARTIFACT_ACCESS_TOKEN }} 

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Run tests with Firebase Emulators
        run: npm test
        env:
          CI: true
          # Estes secrets virão do ambiente 'test' configurado no GitHub
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }} 
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.TEST_FIREBASE_API_KEY }} 
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "localhost" 
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.TEST_FIREBASE_STORAGE_BUCKET }} 
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.TEST_FIREBASE_MESSAGING_SENDER_ID }} 
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.TEST_FIREBASE_APP_ID }} 
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: "http://localhost:9000?ns=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}" 
          FIRESTORE_EMULATOR_HOST: "localhost:8080" 
          FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099" 
          FIREBASE_STORAGE_EMULATOR_HOST: "localhost:9199" 
          FIREBASE_DATABASE_EMULATOR_HOST: "localhost:9000"  
          FUNCTIONS_EMULATOR_HOST: "localhost:5001" 
          FIREBASE_FUNCTIONS_EMULATOR_ORIGIN: "http://localhost:5001" 
          GCLOUD_PROJECT: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }} 
          FIREBASE_CONFIG: "{}" 
          FIREBASE_PROJECT_ID_INTERNAL: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }} 
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
