
# This file has been renamed to 4-deploy-to-firebase-production.yml
# This placeholder indicates it should be removed or was the source for the rename.
# The new production workflow is .github/workflows/4-deploy-to-firebase-production.yml
