name: 2. Build for Deployment

on:
  workflow_run:
    workflows: ['1. Run Integration Tests'] # This name should match the `name` in 1-integration-tests.yml
    types:
      - completed

jobs:
  build_production_package:
    runs-on: ubuntu-latest
    environment: production
    if: >
      github.event.workflow_run.workflow.name == '1. Run Integration Tests' &&
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' || (github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].base.ref == 'main'))

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Prepare Next.js deployment artifact
        run: |
          mkdir -p nextjs-deploy-artifact
          cp -r .next nextjs-deploy-artifact/
          cp -r public nextjs-deploy-artifact/
          cp package.json nextjs-deploy-artifact/
          cp package-lock.json nextjs-deploy-artifact/ 
          cp next.config.mjs nextjs-deploy-artifact/ 
          cp apphosting.yaml nextjs-deploy-artifact/
          if [ -f "tsconfig.json" ]; then cp tsconfig.json nextjs-deploy-artifact/; fi

      - name: Upload Next.js deployment artifact (Production)
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-production
          path: nextjs-deploy-artifact/
          retention-days: 1

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions Shared Files
        run: npm run build:shared --prefix functions
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Prepare Functions deployment artifact
        run: |
          set -e 
          echo "Preparing Functions deployment artifact staging directory..."
          mkdir -p functions_artifact_staging_deploy/src
          mkdir -p functions_artifact_staging_deploy/lib/shared 
          mkdir -p functions_artifact_staging_deploy/node_modules 

          echo "Copying functions/src..."
          cp -r functions/src/* functions_artifact_staging_deploy/src/

          echo "Checking for functions/lib/shared..."
          if [ -d "functions/lib/shared" ]; then
            echo "Copying functions/lib/shared..."
            cp -r functions/lib/shared/* functions_artifact_staging_deploy/lib/shared/
          else
            echo "Error: functions/lib/shared not found after build:shared. Cannot prepare deploy artifact."
            exit 1
          fi

          echo "Copying functions/package.json and package-lock.json..."
          cp functions/package.json functions_artifact_staging_deploy/
          cp functions/package-lock.json functions_artifact_staging_deploy/

          echo "Copying functions/node_modules..."
          if [ -d "functions/node_modules" ]; then
            cp -r functions/node_modules/* functions_artifact_staging_deploy/node_modules/
          else
            echo "Warning: functions/node_modules not found. This might be an issue for deployment if dependencies are expected."
          fi

          echo "Listing contents of Functions deployment staging directory:"
          ls -R functions_artifact_staging_deploy
        shell: bash

      - name: Upload Functions deployment artifact (Production)
        uses: actions/upload-artifact@v4
        with:
          name: functions-build-production
          path: functions_artifact_staging_deploy/
          retention-days: 1
          if-no-files-found: error
