name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [integration-tests, build] # This job needs integration tests and build to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      # Add steps to potentially download build artifacts if they were created in the build job

      - name: Deploy to Firebase
        run: | # Replace with your actual Firebase deploy command
          echo "Running Firebase deploy command..."
          # Example: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

      # Add any other deployment steps
