name: 4. Deploy to Firebase

on:
  workflow_run:
    workflows: ['3. Build for Deployment']
    types:
      - completed

jobs:
  deploy_application:
    runs-on: ubuntu-latest
    environment: production
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Download Next.js build artifact (Production)
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build-production
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.ARTIFACT_ACCESS_TOKEN }}

      - name: Download Functions build artifact (Production)
        uses: actions/download-artifact@v4
        with:
          name: functions-build-production
          path: functions
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.ARTIFACT_ACCESS_TOKEN }}

      - name: Authenticate to Google Cloud (WIF for Functions/Rules)
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Deploy to Firebase App Hosting (Production)
        uses: firebase-tools/action-apphosting-deploy@v0
        with:
          projectId: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
          backendId: ${{ secrets.FIREBASE_BACKEND_ID_PRODUCTION }}
          region: ${{ secrets.GCP_REGION }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy Firebase Functions (Production)
        run: |
          firebase deploy --only functions \
            --project ${{ secrets.NEXT_PUBLIC_PROJECT_ID }} \
            --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_path }}

      - name: Checkout repository for rule files
        uses: actions/checkout@v4

      - name: Deploy Firebase Rules (Firestore, Storage, RTDB) (Production)
        run: |
          firebase deploy --only firestore:rules,storage:rules,database:rules \
            --project ${{ secrets.NEXT_PUBLIC_PROJECT_ID }} \
            --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_path }}
