
name: Run Integration Tests

on: push

jobs:
  test_production:
    name: Test
    runs-on: ubuntu-latest
    environment: test 
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Next.js app dependencies
        run: npm ci

      - name: Install Firebase Functions dependencies
        run: npm ci --prefix functions

      - name: Build Firebase Functions Shared Files (for Emulators)
        run: npm run build:shared --prefix functions
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Get Firebase CLI version
        id: firebase_version
        run: echo "CLI_VERSION=$(firebase --version)" >> $GITHUB_OUTPUT

      - name: Cache Firebase Emulators
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ steps.firebase_version.outputs.CLI_VERSION }}
          restore-keys: |
            ${{ runner.os }}-firebase-emulators-

      - name: Run tests with Firebase Emulators
        run: npm test
        env:
          CI: true
          FIRESTORE_EMULATOR_HOST: ${{ secrets.FIRESTORE_EMULATOR_HOST }}
          FIREBASE_AUTH_EMULATOR_HOST: ${{ secrets.FIREBASE_AUTH_EMULATOR_HOST }}
          FIREBASE_STORAGE_EMULATOR_HOST: ${{ secrets.FIREBASE_STORAGE_EMULATOR_HOST }}
          FIREBASE_DATABASE_EMULATOR_HOST: ${{ secrets.FIREBASE_DATABASE_EMULATOR_HOST }}
          FUNCTIONS_EMULATOR_HOST: ${{ secrets.FUNCTIONS_EMULATOR_HOST }}
          FIREBASE_FUNCTIONS_EMULATOR_ORIGIN: ${{ secrets.FIREBASE_FUNCTIONS_EMULATOR_ORIGIN }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          FIREBASE_WEB_CONFIG: ${{ secrets.FIREBASE_WEB_CONFIG }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}
          NEXT_PUBLIC_FIREBASE_WEB_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_WEB_CONFIG }}
